{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "bluecompute.fullname" . }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "bluecompute.labels" . | indent 4 }}
spec:
  {{- if .Values.ingress.enableTLS }}
  tls:
{{ toYaml .Values.ingress.TLS | indent 4 }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hostnames.app | default "" }}
    http:
      paths:
      - path: {{ .Values.web.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.web.fullnameOverride }}
            port:
              number: {{ .Values.web.service.externalPort }}
  {{- if .Values.auth.enabled }}
  - host: {{ .Values.ingress.hostnames.api | default "" }}
    http:
      paths:
      - path: {{ .Values.auth.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.auth.fullnameOverride }}
            port:
              number: {{ .Values.auth.service.externalPort }}
  {{- end }}
  {{- if .Values.catalog.enabled }}
  - host: {{ .Values.ingress.hostnames.api | default "" }}
    http:
      paths:
      - path: {{ .Values.catalog.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.catalog.fullnameOverride }}
            port:
              number: {{ .Values.catalog.service.externalPort }}
  {{- end }}
  {{- if .Values.customer.enabled }}
  - host: {{ .Values.ingress.hostnames.api | default "" }}
    http:
      paths:
      - path: {{ .Values.customer.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.customer.fullnameOverride }}
            port:
              number: {{ .Values.customer.service.externalPort }}
  {{- end }}
  {{- if .Values.inventory.enabled }}
  - host: {{ .Values.ingress.hostnames.api | default "" }}
    http:
      paths:
      - path: {{ .Values.inventory.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.inventory.fullnameOverride }}
            port:
              number: {{ .Values.inventory.service.externalPort }}
  {{- end }}
  {{- if .Values.orders.enabled }}
  - host: {{ .Values.ingress.hostnames.api | default "" }}
    http:
      paths:
      - path: {{ .Values.orders.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.orders.fullnameOverride }}
            port:
              number: {{ .Values.orders.service.externalPort }}
  {{- end }}
{{- end }}