{{- if and .Values.ingress.enabled .Values.web.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bluecompute.fullname" . }}
  labels:
    {{- include "bluecompute.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.enableTLS }}
  tls:
    {{- range .Values.ingress.TLS }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    # APP Hostnames
    {{- range .Values.ingress.hosts.app }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.web.fullnameOverride }}
                port:
                  number: {{ $.Values.web.service.externalPort }}
    {{- end }}

    # API Hostnames for Auth
    {{- if .Values.auth.enabled }}
    {{- range .Values.ingress.hosts.api }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.auth.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.auth.fullnameOverride }}
                port:
                  number: {{ $.Values.auth.service.externalPort }}
    {{- end }}
    {{- end }}

    # API Hostnames for Catalog
    {{- if .Values.catalog.enabled }}
    {{- range .Values.ingress.hosts.api }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.catalog.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.catalog.fullnameOverride }}
                port:
                  number: {{ $.Values.catalog.service.externalPort }}
    {{- end }}
    {{- end }}

    # API Hostnames for Customer
    {{- if .Values.customer.enabled }}
    {{- range .Values.ingress.hosts.api }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.customer.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.customer.fullnameOverride }}
                port:
                  number: {{ $.Values.customer.service.externalPort }}
    {{- end }}
    {{- end }}

    # API Hostnames for Inventory
    {{- if .Values.inventory.enabled }}
    {{- range .Values.ingress.hosts.api }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.inventory.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.inventory.fullnameOverride }}
                port:
                  number: {{ $.Values.inventory.service.externalPort }}
    {{- end }}
    {{- end }}

    # API Hostnames for Orders
    {{- if .Values.orders.enabled }}
    {{- range .Values.ingress.hosts.api }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.orders.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.orders.fullnameOverride }}
                port:
                  number: {{ $.Values.orders.service.externalPort }}
    {{- end }}
    {{- end }}

  # Fallback default backend if no rules are specified
  {{- if not (or .Values.ingress.hosts.app .Values.ingress.hosts.api) }}
  defaultBackend:
    service:
      name: {{ $.Values.web.fullnameOverride }}
      port:
        number: {{ $.Values.web.service.externalPort }}
  {{- end }}
{{- end }}