{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.web.fullnameOverride }}
  labels:
    {{- include "bluecompute.labels" . | indent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Values.web.fullnameOverride }}
{{- end }}