apiVersion: v1
entries:
  auth:
  - apiVersion: v2
    created: "2024-12-30T15:34:06.477190118Z"
    description: BlueCompute Auth Microservice
    digest: 03e2f4fe0dca9438145bf8c8973e834343aa4ad8c6de398e07aba003f302da32
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-auth
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: auth
    urls:
    - auth-0.6.0.tgz
    version: 0.6.0
  bluecompute:
  - apiVersion: v2
    created: "2024-12-30T15:34:06.515341355Z"
    dependencies:
    - condition: auth.enabled
      name: auth
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: catalog.enabled
      name: catalog
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: customer.enabled
      name: customer
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: inventory.enabled
      name: inventory
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: orders.enabled
      name: orders
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: web.enabled
      name: web
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 12.2.0
    - condition: elasticsearch.enabled
      name: elasticsearch
      repository: https://charts.bitnami.com/bitnami
      version: 21.4.1
    - alias: orders-mysql
      condition: orders-mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 12.2.0
    - condition: couchdb.enabled
      name: couchdb
      repository: https://apache.github.io/couchdb-helm
      version: 4.5.6
    description: BlueCompute Application Chart
    digest: 6bdee5c919137ada1393eb0565f94c445f9b6456a287b1c73f705a18e97b354a
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-kubernetes
    maintainers:
    - email: hello@fabiogomezdiaz.com
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: bluecompute
    urls:
    - bluecompute-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    created: "2024-12-30T15:34:06.489508059Z"
    dependencies:
    - condition: auth.enabled
      name: auth
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: catalog.enabled
      name: catalog
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: customer.enabled
      name: customer
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: inventory.enabled
      name: inventory
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: orders.enabled
      name: orders
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: web.enabled
      name: web
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: mysql.enabled
      name: mysql
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.6.6
    - condition: elasticsearch.enabled
      name: elasticsearch
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.32.5
    - condition: mariadb.enabled
      name: mariadb
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 7.3.14
    - condition: couchdb.enabled
      name: couchdb
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 2.3.0
    description: BlueCompute Application Chart
    digest: 1fd4524846072e8782262dba8db204043084f5e0c05d8a911ea4ba0b6f8decad
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-kubernetes
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: bluecompute
    urls:
    - bluecompute-0.0.9.tgz
    version: 0.0.9
  catalog:
  - apiVersion: v2
    created: "2024-12-30T15:34:06.516100039Z"
    description: BlueCompute Catalog Microservice
    digest: f1dcfa123266701fb7a331d90a2a495f632dd86ce5f9951393d418bef03425b1
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-catalog
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: catalog
    urls:
    - catalog-0.6.0.tgz
    version: 0.6.0
  couchdb:
  - apiVersion: v1
    appVersion: 2.3.1
    created: "2024-12-30T15:34:06.516843462Z"
    deprecated: true
    description: DEPRECATED A database featuring seamless multi-master sync, that
      scales from big data to mobile, with an intuitive HTTP/JSON API and designed
      for reliability.
    digest: 9577e07d34241adfe32426d794004f49bcb80c32d25da957fa5b3c3d4403f494
    home: https://couchdb.apache.org/
    icon: http://couchdb.apache.org/CouchDB-visual-identity/logo/CouchDB-couch-symbol.svg
    keywords:
    - couchdb
    - database
    - nosql
    name: couchdb
    sources:
    - https://github.com/apache/couchdb-docker
    urls:
    - couchdb-2.3.0.tgz
    version: 2.3.0
  customer:
  - apiVersion: v2
    created: "2024-12-30T15:34:06.517721908Z"
    description: BlueCompute Customer Microservice
    digest: 07b7719010086c7de213f3abd7780e4bd8321d2d33aa05d252e3185ef66850ae
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-customer
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: customer
    urls:
    - customer-0.6.0.tgz
    version: 0.6.0
  inventory:
  - apiVersion: v2
    created: "2024-12-30T15:34:06.518596549Z"
    description: BlueCompute Inventory Microservice
    digest: 6af0566852daeb9822de925845e3a5794b699f0af70d687cfbaf2f1e7ba91f6e
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-inventory
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: inventory
    urls:
    - inventory-0.6.0.tgz
    version: 0.6.0
  orders:
  - apiVersion: v2
    created: "2024-12-30T15:34:06.519831496Z"
    description: BlueCompute Orders Microservice
    digest: 1860168a10868848f71379e7b9774b5ad01a73aa69e2c42e869b4ae21af8987d
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-orders
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: orders
    urls:
    - orders-0.6.0.tgz
    version: 0.6.0
  web:
  - apiVersion: v2
    created: "2024-12-30T15:34:06.520799482Z"
    description: BlueCompute Web BFF Microservice
    digest: d2aa8d17150a956c818d0b68b88ea0b1f64831bea087d16f466fc5e9d8028c80
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-web
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: web
    urls:
    - web-0.6.0.tgz
    version: 0.6.0
generated: "2024-12-30T15:34:06.476331915Z"
