apiVersion: v1
entries:
  auth:
  - apiVersion: v2
    created: "2019-10-14T15:50:42.12206-05:00"
    description: BlueCompute Auth Microservice
    digest: f9e24bcbd3068c79957fe8d77ae1467b939e5b50e6ea79710ec4f43e51e343ff
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-auth
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: auth
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/auth-0.6.0.tgz
    version: 0.6.0
  bluecompute:
  - apiVersion: v2
    created: "2019-10-14T15:50:42.133879-05:00"
    dependencies:
    - condition: auth.enabled
      name: auth
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: catalog.enabled
      name: catalog
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: customer.enabled
      name: customer
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: inventory.enabled
      name: inventory
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: orders.enabled
      name: orders
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: web.enabled
      name: web
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: mysql.enabled
      name: mysql
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 0.15.0
    - condition: elasticsearch.enabled
      name: elasticsearch
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.21.1
    - condition: mariadb.enabled
      name: mariadb
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 5.5.3
    - condition: couchdb.enabled
      name: couchdb
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 1.1.1
    description: BlueCompute Application Chart
    digest: b4775453b93757d1323cdfa2ce61c721c838115a75f8a93d337004eeb40013b0
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-kubernetes
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: bluecompute
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/bluecompute-0.0.9.tgz
    version: 0.0.9
  catalog:
  - apiVersion: v2
    created: "2019-10-14T15:50:42.13467-05:00"
    description: BlueCompute Catalog Microservice
    digest: ceb2bddbf4f01cf78ebcc0ada6b4573d1a28f6110260dacf8132a7e778155f5b
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-catalog
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: catalog
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/catalog-0.6.0.tgz
    version: 0.6.0
  couchdb:
  - apiVersion: v1
    appVersion: 2.3.0
    created: "2019-10-14T15:50:42.136202-05:00"
    description: A database featuring seamless multi-master sync, that scales from
      big data to mobile, with an intuitive HTTP/JSON API and designed for reliability.
    digest: 2e41d05cf62d7bbe598b3f3ff36bd76195209b06c800fffd85e236fa98a91159
    home: https://couchdb.apache.org/
    icon: http://couchdb.apache.org/CouchDB-visual-identity/logo/CouchDB-couch-symbol.svg
    maintainers:
    - email: kocolosk@apache.org
      name: kocolosk
    name: couchdb
    sources:
    - https://github.com/apache/couchdb
    - https://github.com/kocolosk/couchdb-statefulset-assembler
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/couchdb-1.1.1.tgz
    version: 1.1.1
  customer:
  - apiVersion: v2
    created: "2019-10-14T15:50:42.136948-05:00"
    description: BlueCompute Customer Microservice
    digest: 17b98c8816c57b9e43aa6f2ce804c116704d712d789ea472b88bdef482e4d535
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-customer
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: customer
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/customer-0.6.0.tgz
    version: 0.6.0
  inventory:
  - apiVersion: v2
    created: "2019-10-14T15:50:42.137781-05:00"
    description: BlueCompute Inventory Microservice
    digest: 82838a70ba25af38fc6433ce46dd00d81cb79bdc0d36a41c0a752798af60b5c7
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-inventory
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: inventory
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/inventory-0.6.0.tgz
    version: 0.6.0
  orders:
  - apiVersion: v2
    created: "2019-10-14T15:50:42.138484-05:00"
    description: BlueCompute Orders Microservice
    digest: 0525c78b46b31aee52241ae02e506305fd2c0ed15b7e5da246069cfaf1948693
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-orders
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: orders
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/orders-0.6.0.tgz
    version: 0.6.0
  web:
  - apiVersion: v2
    created: "2019-10-14T15:50:42.139169-05:00"
    description: BlueCompute Web BFF Microservice
    digest: 5dd2eda8484ce4f999f8bae17f00fce4c6b50043fe5696e55bed9747f980f5a9
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-web
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: web
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/web-0.6.0.tgz
    version: 0.6.0
generated: "2019-10-14T15:50:42.120897-05:00"
