apiVersion: v1
entries:
  auth:
  - apiVersion: v2
    created: "2020-07-11T18:16:38.634058-05:00"
    description: BlueCompute Auth Microservice
    digest: 03e2f4fe0dca9438145bf8c8973e834343aa4ad8c6de398e07aba003f302da32
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-auth
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: auth
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/auth-0.6.0.tgz
    version: 0.6.0
  bluecompute:
  - apiVersion: v2
    created: "2020-07-11T18:16:38.647754-05:00"
    dependencies:
    - condition: auth.enabled
      name: auth
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: catalog.enabled
      name: catalog
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: customer.enabled
      name: customer
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: inventory.enabled
      name: inventory
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: orders.enabled
      name: orders
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: web.enabled
      name: web
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: mysql.enabled
      name: mysql
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.6.6
    - condition: elasticsearch.enabled
      name: elasticsearch
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.32.5
    - condition: mariadb.enabled
      name: mariadb
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 7.3.14
    - condition: couchdb.enabled
      name: couchdb
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 2.3.0
    description: BlueCompute Application Chart
    digest: 504f96024fd0e389dbcf8edd711c0ea4cc8c55afedd1998951e58a3e1857335e
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-kubernetes
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: bluecompute
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/bluecompute-0.0.9.tgz
    version: 0.0.9
  catalog:
  - apiVersion: v2
    created: "2020-07-11T18:16:38.648938-05:00"
    description: BlueCompute Catalog Microservice
    digest: f1dcfa123266701fb7a331d90a2a495f632dd86ce5f9951393d418bef03425b1
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-catalog
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: catalog
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/catalog-0.6.0.tgz
    version: 0.6.0
  couchdb:
  - apiVersion: v1
    appVersion: 2.3.1
    created: "2020-07-11T18:16:38.649984-05:00"
    deprecated: true
    description: DEPRECATED A database featuring seamless multi-master sync, that
      scales from big data to mobile, with an intuitive HTTP/JSON API and designed
      for reliability.
    digest: 9577e07d34241adfe32426d794004f49bcb80c32d25da957fa5b3c3d4403f494
    home: https://couchdb.apache.org/
    icon: http://couchdb.apache.org/CouchDB-visual-identity/logo/CouchDB-couch-symbol.svg
    keywords:
    - couchdb
    - database
    - nosql
    name: couchdb
    sources:
    - https://github.com/apache/couchdb-docker
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/couchdb-2.3.0.tgz
    version: 2.3.0
  customer:
  - apiVersion: v2
    created: "2020-07-11T18:16:38.65125-05:00"
    description: BlueCompute Customer Microservice
    digest: 07b7719010086c7de213f3abd7780e4bd8321d2d33aa05d252e3185ef66850ae
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-customer
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: customer
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/customer-0.6.0.tgz
    version: 0.6.0
  inventory:
  - apiVersion: v2
    created: "2020-07-11T18:16:38.652469-05:00"
    description: BlueCompute Inventory Microservice
    digest: 6af0566852daeb9822de925845e3a5794b699f0af70d687cfbaf2f1e7ba91f6e
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-inventory
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: inventory
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/inventory-0.6.0.tgz
    version: 0.6.0
  orders:
  - apiVersion: v2
    created: "2020-07-11T18:16:38.653563-05:00"
    description: BlueCompute Orders Microservice
    digest: 1860168a10868848f71379e7b9774b5ad01a73aa69e2c42e869b4ae21af8987d
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-orders
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: orders
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/orders-0.6.0.tgz
    version: 0.6.0
  web:
  - apiVersion: v2
    created: "2020-07-11T18:16:38.655108-05:00"
    description: BlueCompute Web BFF Microservice
    digest: d2aa8d17150a956c818d0b68b88ea0b1f64831bea087d16f466fc5e9d8028c80
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-web
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: web
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/web-0.6.0.tgz
    version: 0.6.0
generated: "2020-07-11T18:16:38.63277-05:00"
