apiVersion: v1
entries:
  auth:
  - apiVersion: v1
    created: "2019-09-24T13:08:25.302212-05:00"
    description: BlueCompute Auth Microservice
    digest: 3e2bc1f36d72cfcb70396d4b7d62c0e97c67db614a769dab64c955edd0114f24
    name: auth
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/auth-0.6.0.tgz
    version: 0.6.0
  catalog:
  - apiVersion: v1
    created: "2019-09-24T13:08:25.303042-05:00"
    description: BlueCompute Catalog Microservice
    digest: 890be60fbc561490d43370edc7bb268d40518a927cfbbc68ef74026647505749
    name: catalog
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/catalog-0.6.0.tgz
    version: 0.6.0
  couchdb:
  - apiVersion: v1
    appVersion: 2.3.0
    created: "2019-09-24T13:08:25.306173-05:00"
    description: A database featuring seamless multi-master sync, that scales from
      big data to mobile, with an intuitive HTTP/JSON API and designed for reliability.
    digest: 2e41d05cf62d7bbe598b3f3ff36bd76195209b06c800fffd85e236fa98a91159
    home: https://couchdb.apache.org/
    icon: http://couchdb.apache.org/CouchDB-visual-identity/logo/CouchDB-couch-symbol.svg
    maintainers:
    - email: kocolosk@apache.org
      name: kocolosk
    name: couchdb
    sources:
    - https://github.com/apache/couchdb
    - https://github.com/kocolosk/couchdb-statefulset-assembler
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/couchdb-1.1.1.tgz
    version: 1.1.1
  customer:
  - apiVersion: v1
    created: "2019-09-24T13:08:25.307699-05:00"
    description: BlueCompute Customer Microservice
    digest: 1a1c768090c5d75b5aec21e392b663f81b9f128c5969211c0dc193d99dff97eb
    name: customer
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/customer-0.6.0.tgz
    version: 0.6.0
  inventory:
  - apiVersion: v1
    created: "2019-09-24T13:08:25.30853-05:00"
    description: BlueCompute Inventory Microservice
    digest: d84e9126ab97e3856ff17240d96aa796949dd63efbb751d21d80ef02f69bd22b
    name: inventory
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/inventory-0.6.0.tgz
    version: 0.6.0
  orders:
  - apiVersion: v1
    created: "2019-09-24T13:08:25.30921-05:00"
    description: Bluecompute Orders Microservice
    digest: 5ca2261c2801362d1fa742fec4c3ecd8ef247df7aecb2c29326f898a76b739ed
    name: orders
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/orders-0.6.0.tgz
    version: 0.6.0
  web:
  - apiVersion: v1
    created: "2019-09-24T13:08:25.309886-05:00"
    description: BlueCompute Web BFF app
    digest: a37defd5b1eaa1813329cbb61f58facc7776e38b43a4390e12d9627006d890ea
    name: web
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/web-0.6.0.tgz
    version: 0.6.0
generated: "2019-09-24T13:08:25.301244-05:00"
