apiVersion: v1
entries:
  auth:
  - apiVersion: v2
    created: "2020-07-10T14:08:48.296197-05:00"
    description: BlueCompute Auth Microservice
    digest: b3c50fc8831fbc8f4545d6b89016916039f2b1654e4455d98a80a1da40199408
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-auth
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: auth
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/auth-0.6.0.tgz
    version: 0.6.0
  bluecompute:
  - apiVersion: v2
    created: "2020-07-10T14:08:48.307644-05:00"
    dependencies:
    - condition: auth.enabled
      name: auth
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: catalog.enabled
      name: catalog
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: customer.enabled
      name: customer
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: inventory.enabled
      name: inventory
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: orders.enabled
      name: orders
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: web.enabled
      name: web
      repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
      version: 0.6.0
    - condition: mysql.enabled
      name: mysql
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.6.6
    - condition: elasticsearch.enabled
      name: elasticsearch
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.32.5
    - condition: mariadb.enabled
      name: mariadb
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 7.3.14
    - condition: couchdb.enabled
      name: couchdb
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 2.3.0
    description: BlueCompute Application Chart
    digest: 2cbd0340465f0fea479a1940009e56d1de69376d82dc025efbb829d4314bb1d5
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-kubernetes
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: bluecompute
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/bluecompute-0.0.9.tgz
    version: 0.0.9
  catalog:
  - apiVersion: v2
    created: "2020-07-10T14:08:48.308579-05:00"
    description: BlueCompute Catalog Microservice
    digest: 01b5b53af9b018576ce5af5c904508f00550ca29d5410806b0db0edf00c173b9
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-catalog
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: catalog
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/catalog-0.6.0.tgz
    version: 0.6.0
  couchdb:
  - apiVersion: v1
    appVersion: 2.3.1
    created: "2020-07-10T14:08:48.309433-05:00"
    deprecated: true
    description: DEPRECATED A database featuring seamless multi-master sync, that
      scales from big data to mobile, with an intuitive HTTP/JSON API and designed
      for reliability.
    digest: 0677af67ae1d623ce2aa917e0690f9df135fd092acf9610ab8714211c82b60f3
    home: https://couchdb.apache.org/
    icon: http://couchdb.apache.org/CouchDB-visual-identity/logo/CouchDB-couch-symbol.svg
    keywords:
    - couchdb
    - database
    - nosql
    name: couchdb
    sources:
    - https://github.com/apache/couchdb-docker
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/couchdb-2.3.0.tgz
    version: 2.3.0
  customer:
  - apiVersion: v2
    created: "2020-07-10T14:08:48.310429-05:00"
    description: BlueCompute Customer Microservice
    digest: f76ad623003ce469e0e0dbc02d6c7dced0a9605605098ded18ef48d66fa00aa5
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-customer
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: customer
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/customer-0.6.0.tgz
    version: 0.6.0
  inventory:
  - apiVersion: v2
    created: "2020-07-10T14:08:48.311432-05:00"
    description: BlueCompute Inventory Microservice
    digest: 8912efef8956c0566cd5be199c2b431bbc4c2d806e35a9dbfc348be5be1585df
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-inventory
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: inventory
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/inventory-0.6.0.tgz
    version: 0.6.0
  orders:
  - apiVersion: v2
    created: "2020-07-10T14:08:48.312396-05:00"
    description: BlueCompute Orders Microservice
    digest: ef17af3c21bb9881dc08e7ea416b15014bc7193a84cbc79ba02ce3b6b32e0433
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-orders
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: orders
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/orders-0.6.0.tgz
    version: 0.6.0
  web:
  - apiVersion: v2
    created: "2020-07-10T14:08:48.313417-05:00"
    description: BlueCompute Web BFF Microservice
    digest: 90f8c5635964c6fb547f699c8b55ae0da5e3272acec53aa560f3bc0f8b5b6faf
    home: https://github.com/fabiogomezdiaz/refarch-cloudnative-micro-web
    maintainers:
    - email: fabio.gomez@ieee.org
      name: Fabio Gomez
      url: https://github.com/fabiogomezdiaz
    name: web
    urls:
    - https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts/web-0.6.0.tgz
    version: 0.6.0
generated: "2020-07-10T14:08:48.294658-05:00"
