apiVersion: v2
name: bluecompute
version: 0.0.9
description: BlueCompute Application Chart
home: https://github.com/fabiogomezdiaz/refarch-cloudnative-kubernetes
maintainers:
  - name: Fabio Gomez
    email: fabio.gomez@ieee.org
    url: https://github.com/fabiogomezdiaz
dependencies:
  - name: auth
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: auth.enabled
  - name: catalog
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: catalog.enabled
  - name: customer
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: customer.enabled
  - name: inventory
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: inventory.enabled
  - name: orders
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: orders.enabled
  - name: web
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: web.enabled
  - name: mysql
    version: 0.15.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mysql.enabled
  - name: elasticsearch
    version: 1.21.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: elasticsearch.enabled
  - name: mariadb
    version: 5.5.3
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mariadb.enabled
  - name: couchdb
    version: 1.1.1
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: couchdb.enabled