apiVersion: v2
name: bluecompute
version: 0.1.0
description: BlueCompute Application Chart
home: https://github.com/fabiogomezdiaz/refarch-cloudnative-kubernetes
maintainers:
  - name: Fabio Gomez
    email: hello@fabiogomezdiaz.com
    url: https://github.com/fabiogomezdiaz
dependencies:
  - name: auth
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: auth.enabled
  - name: catalog
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: catalog.enabled
  - name: customer
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: customer.enabled
  - name: inventory
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: inventory.enabled
  - name: orders
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: orders.enabled
  - name: web
    version: 0.6.0
    repository: https://raw.githubusercontent.com/fabiogomezdiaz/refarch-cloudnative-kubernetes/master/charts
    condition: web.enabled
  - name: mysql
    version: 12.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: elasticsearch
    version: 21.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: mysql
    alias: orders-mysql
    version: 12.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: orders-mysql.enabled
  - name: couchdb
    version: 4.5.6
    repository: https://apache.github.io/couchdb-helm
    condition: couchdb.enabled